#!/bin/bash

function fix_chapter_numbers() {
  N=$(ls | sed "s/[^0-9]*//" | sed "s/[^0-9].*//" | sed "s/^0*//" | wc -L)
  for oname in *; do
    nname=$(echo $oname | sed "s/0*\([0-9]\{$N\}\)/([^0-9]\+.*)/\1\2/")
    nname=$(echo $nname | sed -r ":r;s/\b[0-9]{1,$(($N-1))}\b/0&/;tr")
    nname=$(echo $nname | sed 's/\([0-9]\+\)[.-~]\+0*\([1-9]\)\./\1~\2./')
    echo $oname '->' $nname
    mv "$oname" "$nname" 2> /dev/null
  done
}

function merge() {
  local manga_name="$1"
  local manga_input=$(realpath ~/Documents/Mangas/"$1")
  local manga_output=$(realpath ~/Documents/Mangas/Merged/"$1")
  rm "$manga_output"/* -rf
  mkdir "$manga_output" 2> /dev/null
  local i=0
  local total_volumes=$(ls "$manga_input" | wc -l)
  for vol_path in "$manga_input"/*; do
    vol_name=$(basename "$vol_path" | sed 's/volume[^0-9]*//')
    local print_i=$(printf "%0${#total_volumes[@]}d" $i)
    echo "[$print_i/$total_volumes] $vol" >&2
    #local extract_output=$(extract_multiple "$vol" "$manga_output")
    merge_volume "$vol_path" "$manga_name - Volume $vol_name" "$manga_output"
    local i=$(("$i"+1))
  done
  local print_i=$(printf "%0${#total_volumes[@]}d" $i)
  echo "[$print_i/$total_volumes] $vol" >&2
}

function merge_volume() {
  local volume_path="$1"
  local volume_name="$2.cbz"
  local dest="$3"

  pushd "$volume_path" > /dev/null
  pages_dir=$(mktemp -d)
  for chapter in *; do
    chapter_name=$(basename $chapter)
    pushd $chapter > /dev/null
    for page in *.{jpg,png}; do
      cp $page $pages_dir/$chapter_name-$page 2> /dev/null
    done
    popd > /dev/null
  done
  pushd $pages_dir > /dev/null
  zip "$volume_name" ./*.{jpg,png} > /dev/null
  mv "$volume_name" "$dest"
  popd > /dev/null
  rm $pages_dir -rf

  popd > /dev/null
}

function check_for_cover() {
  local from=$1
  local to=$2
  local input="$from"/$(ls "$from" | grep 'cover' | head -1)
  if [ -f "$input" ]; then
    local output="$to"/$(basename "$input")
    cp "$input" "$output"
    if [ -z $(echo $output | grep '\.(jpg|png)') ]; then
      mogrify -format jpg "$output"
      rm "$output"
      local output="$to"/$(ls "$to" | grep 'cover' | head -1)
    fi
    mv "$output" "$to/0.jpg"
  fi
}

function put_in_volume() {
  local vol_number=$1
  if [ "$vol_number" = "--auto" ]; then
    local volumes=$(ls | grep volume | wc -l)
    local vol_number=$(($volumes+1))
  fi
  local folder_name="volume_"$(printf "%02d" "$vol_number")
  local chapters="${@:2}"

  mkdir "$folder_name" 2> /dev/null
  for chapter in $chapters; do
    mv "$chapter"{,.*} "$folder_name" 2> /dev/null
  done
}

[ "$1" == "fix_chapter_numbers" ] && fix_chapter_numbers && exit
[ "$1" == "merge" ]               && merge "$2"          && exit
[ "$1" == "put_in_volume" ]       && put_in_volume "$2" "${@:3}" && exit

